language: node_js
node_js: stable

install:
  - npm install

script:
  - npm run specs
  - npm test

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm start &
  - sleep 3 # give Web server some time
