language: node_js
sudo: false
node_js: node

install:
  - npm install

script:
  - npm test
  - npm run specs

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm start &
  - sleep 3 # give Web server some time
